version: "3"
services:
  hexo-build:
    image: linguochi/hexo-build
    container_name: hexo-build
    volumes:
      - /opt:/app
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    privileged: true
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  lingc-server:
    image: linguochi/hexo-blog
    container_name: hexo-blog
    depends_on:
      - letsencrypt
    environment:
      - VIRTUAL_HOST=linguochi.com
      - LETSENCRYPT_HOST=linguochi.com
      - LETSENCRYPT_EMAIL=linguochi@gmail.com
    volumes:
      - /opt:/app
  lingc-webhook:
    image: linguochi/lingc-webhook
    container_name: lingc-webhook
    depends_on:
      - lingc-server
    environment:
      - VIRTUAL_HOST=deploy.linguochi.com
      - LETSENCRYPT_HOST=deploy.linguochi.com
      - LETSENCRYPT_EMAIL=linguochi@gmail.com
    volumes:
      - /opt:/app
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
